### ISSUE TITLE
publish package

### ISSUE THREAD

**Issue by wtho** [ImmoweltGroup/aws-swiss-knife#2]
`npm run i -g @immowelt/aws-swiss-knife` does result in an error. 

https://www.npmjs.com/login?next=/package/@immowelt/aws-swiss-knife does also not exist yet (or it is not public).

**Comment by denniskribl** [comment]
hey @wtho 

this project is work in progress. We are currently working on integrating the release pipeline. However we could also publish a beta build already to get your hands on.

i'll add the information about the wip status to the readme.

thanks for your input it is highly appreciated :slightly_smiling_face:

**Comment by denniskribl** [comment]
welp I've changed my mind. :smile: Just added the github workflow for it and released [version 1.0.0](https://www.npmjs.com/package/@immowelt/aws-swiss-knife/v/1.0.0) 

I'll create additional issues for semantic releases and some other housekeeping stuff like renovate bot.

Thanks again, more input is always appreciated :slightly_smiling_face:
